name: PiGallery2
version: "1.0.0"
slug: pigallery2
description: Photo gallery and slideshow server
url: https://github.com/bpatrik/pigallery2

arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
apparmor: true
ingress: true
panel_icon: mdi:image-album
panel_title: PiGallery2
ingress_port: 1978

# Host network access is required 
host_network: true
ports:
  1978/tcp: 1978

map:
  - media:ro 
